// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp63gXur4e0ZyPj18_GrdYnSVLFa358-s',
    appId: '1:163020004356:web:a5a23a738930843f562951',
    messagingSenderId: '163020004356',
    projectId: 'resourse-85534',
    authDomain: 'resourse-85534.firebaseapp.com',
    storageBucket: 'resourse-85534.firebasestorage.app',
    measurementId: 'G-75Y4CRHHP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MqKkgXxt1tXuJqjGF66oKcpptSBxOXo',
    appId: '1:163020004356:android:068832cda675ae6e562951',
    messagingSenderId: '163020004356',
    projectId: 'resourse-85534',
    storageBucket: 'resourse-85534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4pm-mmCF5v1ejGKPRVwyhMiKHeqyFvBY',
    appId: '1:163020004356:ios:feccf9ef4df4ddbc562951',
    messagingSenderId: '163020004356',
    projectId: 'resourse-85534',
    storageBucket: 'resourse-85534.firebasestorage.app',
    iosBundleId: 'com.example.resourceBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4pm-mmCF5v1ejGKPRVwyhMiKHeqyFvBY',
    appId: '1:163020004356:ios:feccf9ef4df4ddbc562951',
    messagingSenderId: '163020004356',
    projectId: 'resourse-85534',
    storageBucket: 'resourse-85534.firebasestorage.app',
    iosBundleId: 'com.example.resourceBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp63gXur4e0ZyPj18_GrdYnSVLFa358-s',
    appId: '1:163020004356:web:a3cf785d8c3fa4a7562951',
    messagingSenderId: '163020004356',
    projectId: 'resourse-85534',
    authDomain: 'resourse-85534.firebaseapp.com',
    storageBucket: 'resourse-85534.firebasestorage.app',
    measurementId: 'G-JV6C5FYJNQ',
  );

}