// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArFSY5gfZooo4DuZnKtjVWVWcWUJxCmxc',
    appId: '1:510279142709:web:d68d5b9c6b1b704dbd907c',
    messagingSenderId: '510279142709',
    projectId: 'resource-booking-app',
    authDomain: 'resource-booking-app.firebaseapp.com',
    storageBucket: 'resource-booking-app.firebasestorage.app',
    measurementId: 'G-DM8F0HEGMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-D2UWI6ZdWsoPpStG9EDv2S5J9a7Or0',
    appId: '1:510279142709:android:1c55ec7ef54b56a1bd907c',
    messagingSenderId: '510279142709',
    projectId: 'resource-booking-app',
    storageBucket: 'resource-booking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmbpbgL0sTbFWeu3xCsjf7h0mdRk7hPA',
    appId: '1:510279142709:ios:7ace5336d3a2de78bd907c',
    messagingSenderId: '510279142709',
    projectId: 'resource-booking-app',
    storageBucket: 'resource-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.resourceBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmbpbgL0sTbFWeu3xCsjf7h0mdRk7hPA',
    appId: '1:510279142709:ios:7ace5336d3a2de78bd907c',
    messagingSenderId: '510279142709',
    projectId: 'resource-booking-app',
    storageBucket: 'resource-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.resourceBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArFSY5gfZooo4DuZnKtjVWVWcWUJxCmxc',
    appId: '1:510279142709:web:6ccdde5d647dd172bd907c',
    messagingSenderId: '510279142709',
    projectId: 'resource-booking-app',
    authDomain: 'resource-booking-app.firebaseapp.com',
    storageBucket: 'resource-booking-app.firebasestorage.app',
    measurementId: 'G-HS15KGJ6FR',
  );

}